.TH "build Directory Reference" 3 "Fri Mar 15 2019" "Version 0.1" "Search Algorithms Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbinary\-search\&.d\fP"
.br
.ti -1c
.RI "file \fBcall\-search\&.d\fP"
.br
.ti -1c
.RI "file \fBexecute\-search\&.d\fP"
.br
.ti -1c
.RI "file \fBfibonacci\-search\&.d\fP"
.br
.ti -1c
.RI "file \fBfill\-array\&.d\fP"
.br
.ti -1c
.RI "file \fBjump\-search\&.d\fP"
.br
.ti -1c
.RI "file \fBlinear\-search\&.d\fP"
.br
.ti -1c
.RI "file \fBmain\&.d\fP"
.br
.ti -1c
.RI "file \fBprint\-duration\&.d\fP"
.br
.ti -1c
.RI "file \fBread\-input\&.d\fP"
.br
.ti -1c
.RI "file \fBternary\-search\&.d\fP"
.br
.in -1c
