.TH "src Directory Reference" 3 "Fri Mar 15 2019" "Version 0.1" "Search Algorithms Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbinary\-search\&.cpp\fP"
.br
.RI "Implements the binary search\&. "
.ti -1c
.RI "file \fBcall\-search\&.cpp\fP"
.br
.RI "Call the search function from choice of the user\&. "
.ti -1c
.RI "file \fBexecute\-search\&.cpp\fP"
.br
.RI "Performs searches\&. "
.ti -1c
.RI "file \fBfibonacci\-search\&.cpp\fP"
.br
.RI "Implements the fibonacci search\&. "
.ti -1c
.RI "file \fBfill\-array\&.cpp\fP"
.br
.RI "Fill the array for the search\&. "
.ti -1c
.RI "file \fBjump\-search\&.cpp\fP"
.br
.RI "Implements the jump search\&. "
.ti -1c
.RI "file \fBlinear\-search\&.cpp\fP"
.br
.RI "Implements the linear search\&. "
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprint\-duration\&.cpp\fP"
.br
.RI "Print the search duration time\&. "
.ti -1c
.RI "file \fBread\-input\&.cpp\fP"
.br
.RI "Read the input from the user\&. "
.ti -1c
.RI "file \fBternary\-search\&.cpp\fP"
.br
.RI "Implements the ternary search\&. "
.in -1c
