.TH "include/fill-array.h" 3 "Fri Mar 15 2019" "Version 0.1" "Search Algorithms Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fill-array.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iterator>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfillArray\fP (long *array, long beginRange, int size)"
.br
.RI "Fill the array for the search\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fillArray (long * array, long beginRange, int size)"

.PP
Fill the array for the search\&. 
.PP
\fBParameters:\fP
.RS 4
\fIarray\fP Pointer to the array\&. 
.br
\fIsize\fP Size of the array\&. 
.RE
.PP

.PP
Definition at line 8 of file fill\-array\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Search Algorithms Analysis from the source code\&.
