.TH "src/main.cpp" 3 "Fri Mar 15 2019" "Version 0.1" "Search Algorithms Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/read\-input\&.h'\fP
.br
\fC#include '\&.\&./include/fill\-array\&.h'\fP
.br
\fC#include '\&.\&./include/execute\-search\&.h'\fP
.br
\fC#include '\&.\&./include/result\-write\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jefferson Bruno, Ranieri Santos 
.RE
.PP
\fBDate:\fP
.RS 4
16/03/2019 
.RE
.PP

.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 12 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Search Algorithms Analysis from the source code\&.
