.TH "src/main.cpp" 3 "Sun Mar 10 2019" "Version 1.0" "Algorithms Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- TODO\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/fill\-array\&.h'\fP
.br
\fC#include '\&.\&./include/call\-search\&.h'\fP
.br
\fC#include '\&.\&./include/print\-duration\&.h'\fP
.br
\fC#include '\&.\&./include/linear\-search\&.h'\fP
.br
\fC#include '\&.\&./include/binary\-search\&.h'\fP
.br
\fC#include '\&.\&./include/ternary\-search\&.h'\fP
.br
\fC#include '\&.\&./include/jump\-search\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
TODO\&. 


.PP
\fBAuthor:\fP
.RS 4
Jefferson Bruno, Ranieri Santos 
.RE
.PP
\fBDate:\fP
.RS 4
march, 16th 
.RE
.PP

.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 16 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Algorithms Analysis from the source code\&.
