.TH "src/print-duration.cpp" 3 "Fri Mar 15 2019" "Version 0.1" "Search Algorithms Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print-duration.cpp \- Print the search duration time\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/print\-duration\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintDuration\fP (std::chrono::nanoseconds diff)"
.br
.RI "Print the search duration time\&. "
.in -1c
.SH "Detailed Description"
.PP 
Print the search duration time\&. 


.PP
Definition in file \fBprint\-duration\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void printDuration (std::chrono::nanoseconds diff)"

.PP
Print the search duration time\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdiff\fP Difference between the start and end point\&. 
.RE
.PP

.PP
Definition at line 8 of file print\-duration\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Search Algorithms Analysis from the source code\&.
